/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zlove_jni_ndk_JniUtils */

#ifndef _Included_com_zlove_jni_ndk_JniUtils
#define _Included_com_zlove_jni_ndk_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zlove_jni_ndk_JniUtils
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zlove_jni_ndk_JniUtils_getStringFromNative
  (JNIEnv *, jobject);

/*
 * Class:     com_zlove_jni_ndk_JniUtils
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_zlove_jni_ndk_JniUtils_square__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zlove_jni_ndk_JniUtils
 * Method:    square
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_com_zlove_jni_ndk_JniUtils_square__F
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_zlove_jni_ndk_JniUtils
 * Method:    square
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_zlove_jni_ndk_JniUtils_square__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_zlove_jni_ndk_JniUtils
 * Method:    greetings
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zlove_jni_ndk_JniUtils_greetings
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zlove_jni_ndk_JniUtils
 * Method:    getTwoArray
 * Signature: (I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_zlove_jni_ndk_JniUtils_getTwoArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zlove_jni_ndk_JniUtils
 * Method:    nativeSetName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zlove_jni_ndk_JniUtils_nativeSetName
  (JNIEnv *, jobject);

/*
 * Class:     com_zlove_jni_ndk_JniUtils
 * Method:    doCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zlove_jni_ndk_JniUtils_doCallback
  (JNIEnv *, jobject);

/*
 * Class:     com_zlove_jni_ndk_JniUtils
 * Method:    nativeGetUser
 * Signature: ()Lcom/zlove/jni/ndk/User;
 */
JNIEXPORT jobject JNICALL Java_com_zlove_jni_ndk_JniUtils_nativeGetUser
  (JNIEnv *, jobject);

/*
 * Class:     com_zlove_jni_ndk_JniUtils
 * Method:    printUserInfoAtNative
 * Signature: (Lcom/zlove/jni/ndk/User;)V
 */
JNIEXPORT void JNICALL Java_com_zlove_jni_ndk_JniUtils_printUserInfoAtNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_zlove_jni_ndk_JniUtils
 * Method:    changeUserInfo
 * Signature: (Lcom/zlove/jni/ndk/User;)Lcom/zlove/jni/ndk/User;
 */
JNIEXPORT jobject JNICALL Java_com_zlove_jni_ndk_JniUtils_changeUserInfo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_zlove_jni_ndk_JniUtils
 * Method:    nativeGetUserList
 * Signature: (I)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_zlove_jni_ndk_JniUtils_nativeGetUserList
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
